[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"


[project]
name = "autocraftofexile"
version = "0.2.0"
description = "Console application for automating Craft of Exile recipes"
readme = "README.md"
authors = [{ name = "ProphetLamb", email = "prophet.lamb@gmail.com" }]
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
urls = { Repository = "https://github.com/ProphetLamb/autocraftofexile.git", GitHub = "https://github.com/ProphetLamb/autocraftofexile" }

requires-python = ">=3.14"

dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "requests>=2.32",
    "pywinctl>=0.4.1",
    "typer>=0.27.0",
    "pytweening>=1.2.0",
    "pyperclip>=1.11.0",
    "uv>=0.12.0",
    "opencv-python>=5.0.0.93",
]

[project.optional-dependencies]
dev = ["pytest>=8.0"]


[project.scripts]
autocraftofexile = "autocraftofexile.main:app"


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = ["--import-mode=importlib", "-ra"]

[tool.uv.workspace]
members = []
